config/routes.rb
Rails.application.routes.draw do
  resources :journeys do
  member do
    get 'download_file'
    end
  end

  root 'journeys#index'

end

app/models/journey.rb
class Journey < ActiveRecord::Base
  mount_uploader :data, DataUploader
  validates_presence_of :name, :data

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  before_action :set_journey, only: [:show, :edit, :update, :destroy]

  # GET /journeys
  # GET /journeys.json
  def index
    @journeys = Journey.all
  end

  # GET /journeys/1
  # GET /journeys/1.json
  def show
  end

  # GET /journeys/new
  def new
    @journey = Journey.new
  end

  # GET /journeys/1/edit
  def edit
  end

  # POST /journeys
  # POST /journeys.json
  def create
    @journey = Journey.new(journey_params)

    respond_to do |format|
      if @journey.save
        format.html { redirect_to @journey, notice: 'Journey was successfully created.' }
        format.json { render :show, status: :created, location: @journey }
      else
        format.html { render :new }
        format.json { render json: @journey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journeys/1
  # PATCH/PUT /journeys/1.json
  def update
    respond_to do |format|
      if @journey.update(journey_params)
        format.html { redirect_to @journey, notice: 'Journey was successfully updated.' }
        format.json { render :show, status: :ok, location: @journey }
      else
        format.html { render :edit }
        format.json { render json: @journey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journeys/1
  # DELETE /journeys/1.json
  def destroy
    @journey.destroy
    respond_to do |format|
      format.html { redirect_to journeys_url, notice: 'Journey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download_file
    @csv = Journey.find(params[:id])
    send_file(@csv.data.file.path,
          #:filename => @csv.data.file.name,
          :type => @csv.data.file.content_type,
          :disposition => 'attachment',
          :url_based_filename => false)
  end

  def file_to_js


  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journey
      @journey = Journey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journey_params
      params.require(:journey).permit(:name, :data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/journeys_helper.rb
module JourneysHelper
end

app/views/journeys/_form.html.erb
<%= form_for(@journey) do |f| %>
  <% if @journey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@journey.errors.count, "error") %> prohibited this journey from being saved:</h2>

      <ul>
      <% @journey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :data, "CSV File for upload" %><br>
    <%= f.file_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/journeys/edit.html.erb
<h1 class="text-center">Editing Journey</h1>

<%= render 'form' %>
<hr>

<%= link_to 'Show', @journey, :class => "button" %> |
<%= link_to 'Back to List', journeys_path, :class => "button alert" %>

app/views/journeys/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Welcome to the Journey tracker!</h1>
<h2 class="text-center">Instructions</h2>
<p class="text-center">To use this application simply click the create journey button. Give your journey a name and
  upload your CSV with the required data. Once done, the CSV will be processed and you can see
  statistics about the journey.</p>

<div class="center-button">
<%= link_to 'Create Journey', new_journey_path, :class => "button text-center" %>
</div>

<h2 class="text-center">Journeys made so far</h2>
  
<div class="mychart">
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Journey Created</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @journeys.each do |journey| %>
      <tr>
        <td><%= journey.name %></td>
        <td><%= journey.created_at.strftime("%B %d %Y %H:%M") %></td>
        <td><%= link_to 'View', journey %></td>
        <td><%= link_to 'Edit', edit_journey_path(journey) %></td>
        <td><%= link_to 'Delete', journey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/journeys/new.html.erb
<h1 class="text-center">Create a new Journey</h1>

<%= render 'form' %>

<hr>

<div class="center-button">
<%= link_to 'Back', journeys_path, :class => "button alert" %>
</div>

app/views/journeys/show.html.erb
<% content_for :title do "Showing Journey Stats for #{@journey.name}| Journey Tracker" end %>

<h1 class="text-center"><%= @journey.name %></h1>

<div class="center-button">
<%= link_to "Download Raw Data", {:action => 'download_file'}, {:class => ("button")} %>
<%= link_to "Back", root_path, :class => "button alert" %>
</div>

<table>
  <tr>
  <th colspan="5">Journey Statistics<th></tr>
  <tr>
    <th>Max Speed</th>
    <th>Average Speed</th>
    <th>Distance Travelled</th>
    <th>Max Altitude</th>
    <th>Average Altitude</th>
  </tr>
  <tr>
    <td id="maxspeed" class="text-center"></td>
    <td id="averagespeed" class="text-center"></td>
    <td id="distancetravelled" class="text-center"></td>
    <td id="maxalt" class="text-center"></td>
    <td id="avgalt" class="text-center"></td>
  </tr>
</table>
<hr/>
<div class="small-12 large-6 columns">
<h4 class="text-center">Visual Map of the Journey</h4>
<div id="map"></div>

</div>

<div class="small-12 large-6 columns">
<h4 class="text-center">Changes in speed throughout the journey</h4>
<div id="chartContainer"></div>
</div>

<%= javascript_tag do %>

// Functions for calculating distance
// Uses Haversine function from http://www.movable-type.co.uk/scripts/latlong.html

function getDistanceFromLatLonInKm(lat1,lon1,lat2,lon2) {
  var R = 6371; // Radius of the earth in km
  var dLat = deg2rad(lat2-lat1);  // deg2rad below
  var dLon = deg2rad(lon2-lon1);
  var a =
    Math.sin(dLat/2) * Math.sin(dLat/2) +
    Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) *
    Math.sin(dLon/2) * Math.sin(dLon/2)
    ;
  var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
  var d = R * c; // Distance in km
  return d;
}

function deg2rad(deg) {
  return deg * (Math.PI/180)
}

// Set d3 canvas

var margin = {top: 20, right: 20, bottom: 30, left: 50},
    width = 540 - margin.left - margin.right,
    height = 300 - margin.top - margin.bottom;

var parseDate = d3.time.format("%d-%b-%y").parse;

var x = d3.time.scale.utc()
    .range([0, width]);

var y = d3.scale.linear()
    .range([height, 0]);

var xAxis = d3.svg.axis()
    .scale(x)
    .orient("bottom").ticks(10);

var yAxis = d3.svg.axis()
    .scale(y)
    .orient("left");

var line = d3.svg.line()
    .x(function(d) { return x(d.millis); })
    .y(function(d) { return y(d.speed); });

var svg = d3.select("#chartContainer").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

// Global variables for later use

window.long = [];
window.lat  = [];
window.time = [];
window.result = [];

// Read in data

d3.csv("<%= @journey.data.url %>", function(error, data) {
  if (error) throw error;

  data.forEach(function(d) {
    d.millis = new Date(+d.millis);
    d.speed = +d.speed;
    d.altitude = +d.altitude;
    window.lat.push(+d.latitude);
    window.long.push(+d.longitude);
    window.time.push(+d.millis);

  });

  // This section calculates the statistics and appends them to the table

  window.distance = 0;

  for (i = 0; i < lat.length - 1; i++) {
    distance += getDistanceFromLatLonInKm(lat[i],long[i],lat[i+1],long[i+1]);
  };
  console.log(distance);
  document.getElementById("distancetravelled").innerHTML = distance.toFixed(2) + " km";

  var max_speed = d3.max(data, function(d) { return d.speed; });
  console.log(max_speed);
  document.getElementById("maxspeed").innerHTML = max_speed + " km/h";


  var max_alt = d3.max(data, function(d) { return d.altitude; });
  console.log(max_alt);
  document.getElementById("maxalt").innerHTML = max_alt + " ft";


  var avg_alt = d3.sum(data, function(d){
  return d.altitude;
}) / data.length;
console.log(avg_alt);
document.getElementById("avgalt").innerHTML = avg_alt.toFixed(2) + " ft";


  var total_time = ((time[time.length -1]/1000) - (time[0]/1000));
  console.log(total_time);

  avg_ms = ((distance * 1000) / total_time); // Speed in Metres per second
  avg_kmh = (avg_ms * 18)/5; // Convert back to km/h
  console.log(avg_kmh);
  document.getElementById("averagespeed").innerHTML = avg_kmh.toFixed(2) + " km/h";


  x.domain(d3.extent(data, function(d) { return d.millis; }));
  y.domain(d3.extent(data, function(d) { return d.speed; }));

  svg.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + height + ")")
      .call(xAxis);


  svg.append("g")
      .attr("class", "y axis")
      .call(yAxis)
    .append("text")
      .attr("transform", "rotate(-90)")
      .attr("y", 6)
      .attr("dy", ".71em")
      .style("text-anchor", "end")
      .text("Speed");

  svg.append("path")
      .datum(data)
      .attr("class", "line")
      .attr("d", line);

  svg.append("text")
     .attr("x", (width / 2))
     .attr("y", 0 - (margin.top / 2))
     .attr("text-anchor", "middle")
     .style("font-size", "12px")
     .style("text-decoration", "underline")

     // Mapbox

     // Create array of lat/long points

     for ( var i = 0; i < lat.length; i++ ) {
       window.result.push( [lat[i], long[i] ] );
       }

       L.mapbox.accessToken = 'pk.eyJ1IjoicjBja2V0bWFuIiwiYSI6ImNpZ3YyanU1azAwNGR2MGtyc3ZtNGQ3dTkifQ.lowTVPNZRYgbRlMGV-Iqjg';
       var map = L.mapbox.map('map', 'r0cketman.cigv2jtyj003mstly49l00k2k')
           .setView([result[0][0],result[0][1]], 15);
           console.log(window.result);

       // Create array of lat,lon points.
       var line_points = result;


       // Define polyline options
       // http://leafletjs.com/reference.html#polyline
       var polyline_options = {
           color: '#dab737',
           weight: 10
       };

       // Defining a polygon here instead of a polyline will connect the
       // endpoints and fill the path.
       // http://leafletjs.com/reference.html#polygon
       var polyline = L.polyline(line_points, polyline_options).addTo(map);

       // Center journey via lat/long

       map.fitBounds(polyline.getBounds());

});




<% end %>

app/views/layouts/_footer.html.erb
<hr>
<p class="text-center">Made with love, sweat, tears and beer by Mark Sherer</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Welcome to the Journey Tracker" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='https://api.mapbox.com/mapbox.js/v2.2.3/mapbox.css' rel='stylesheet' />
  </head>

  <body>
<div class="row">
  <div class="large-12 columns">
    <%= yield %>
  <%= render 'layouts/footer' %>

</div>
</body>
</html>